if groups | grep 'sudo' >/dev/null; then
    IFS=';' read UPDATES SECURITY_UPDATES < <(sudo /usr/lib/update-notifier/apt-check 2>&1)
    INSTALL=$((UPDATES + SECURITY_UPDATES))
    if (( $INSTALL > 0 )); then
        printf "%d update(s) available\n" "$INSTALL"
    fi
fi

export KUBECONFIG=$HOME/.kube/config-fairview
export KUBE_EDITOR="nvim"
export KUBE_TOKEN=$(cat /opt/k3s/node-token)
